# Tensorflow Fundamentals

In [41]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np

import tensorflow as tf
print(tf.__version__)

2.14.0


## 1. Introduction to Tensor
<p align="center"><img src="./../../assets/img/00-scalar-vector-matrix-tensor.png" width=400></p>

* **scalar**: a single number.                                          `shape=()`, `ndim=0`
* **vector**: a number with direction (e.g. wind speed with direction). `shape=(x, )`, `ndim=1`
* **matrix**: a 2-dimensional array of numbers.                         `shape=(x, y)`, `ndim=2`
* **tensor**: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).                         `shape=(x, y, z)`, `ndim=3`

- For more on the mathematical difference between scalars, vectors and matrices see the [visual algebra post by Math is Fun](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html).


### 1.1. Creating Tensor
- Usually, we dont need create tensors ourselves. 
  - This is because TensorFlow has modules built-in (such as [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) and [`tf.data`](https://www.tensorflow.org/guide/data)) which are able to read your data sources and automatically convert them to tensors

#### 1.1.1 Creating Tensors with `tf.constant()`

In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
scalar.ndim

0

In [3]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

1

In [4]:
# create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [13]:
matrix.ndim

2

In [8]:
another_matrix= tf.constant([[3,2,4,5],
                             [2,3,4,5],
                             [3,4,5,6]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 4), dtype=float16, numpy=
array([[3., 2., 4., 5.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [14]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim # shape=(3,2,3) -> ndim = 3

3

#### 1.1.2. Creating Tensors with [`tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable).

- The difference between `tf.Variable()` and `tf.constant()` is 
  - Tensors created with `tf.constant()` are **immutable** (can't be changed, can only be used to create a new tensor), 
  - Tensors created with `tf.Variable()` are **mutable** (can be changed).
- To change an element of a `tf.Variable()` tensor requires the `assign()` method.

In [18]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [19]:
# Will return error as (requires the .assign() method)
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [20]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

#### 1.1.3. Creating Random Tensors
- Why would you want to create random tensors? 
  - This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.
- For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).

**How a network learns**
![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png)
*A network learns by starting with random patterns (1) then going through demonstrative examples of data (2) whilst trying to update its random patterns to represent the examples (3).*

We can create random tensors by using the [`tf.random.Generator`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class) class.

In [22]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>)

In [23]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [33]:
# Set the global random seed
tf.random.set_seed(42)

random_matrix = tf.random.normal(shape=(2,3))
random_matrix = tf.random.uniform(shape=(2,3))

In [35]:
print(matrix)
print(tf.random.shuffle(matrix))

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


#### 1.1.4. Creating Tensors with [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones), [`tf.zeros()`](https://www.tensorflow.org/api_docs/python/tf/zeros), and [`tf.eye()`](https://www.tensorflow.org/api_docs/python/tf/eye)

In [38]:
# Make a tensor of all ones
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [40]:
# Make a tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [39]:
# Construct one 2 x 3 "identity" matrix
tf.eye(2, num_columns=3)

# Construct a batch of 3 identity matrices, each 2 x 2.
# batch_identity[i, :, :] is a 2 x 2 identity matrix, i = 0, 1, 2.
batch_identity = tf.eye(2, batch_shape=[3])

#### 1.1.5. Creating Tensor from Numpy
- the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.
- `tensor.numpy()` - call on a tensor to convert to an ndarray.


In [42]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

In [77]:
# Convert tensor A to NumPy with .numpy()
A.numpy()

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)

### 1.2. Tensor Information

<p align="center"><img src="./../../assets/img/01-tensor-attributes.png" width=600></p>

In [43]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])

In [44]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [47]:
# Get various attributes of tensor
print("Datatype of every element:  ", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # tf.size return as tensorf so .numpy() converts to NumPy array

Datatype of every element:   <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


### 1.3. Tensor Operations

#### 1.3.1. Tensor Shape Modification
##### Expand / Squeeze Dim
- Expand dim:
  - `tf.newaxis` to expand the new dimensions to your tensor whilst keeping the same information. 
  - [`tf.expand_dims()`](https://www.tensorflow.org/api_docs/python/tf/expand_dims) also can achieve the same
- Squeeze a tensor (removing all single dim):
  - [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.


In [48]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

In [50]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [51]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"

In [52]:
rank_2_tensor.shape, rank_3_tensor.shape

(TensorShape([2, 2]), TensorShape([2, 2, 1]))

In [54]:
tf.expand_dims(rank_2_tensor, axis=-1).numpy() # "-1" means last axis

array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)

In [68]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)

In [72]:
G.shape, G_squeezed.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

##### `tf.reshape()` or `transpose()`

* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape) - allows us to reshape a tensor into a defined shape.
  - Change the shape of the given tensor (first) and then insert values in order they appear (in our case, 1,2,3,4,5,6).
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose) - switches the dimensions of a given tensor.


In [59]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [60]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

#### 1.3.2. Type Casting
- You can change the datatype of a tensor using [`tf.cast()`](https://www.tensorflow.org/api_docs/python/tf/cast).

In [65]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)

#### 1.3.3. Basic Operations
- You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, `+`, `-`, `*`.

##### Squaring, Square Root, Log
* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) - get the square of every value in a tensor. 
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) - get the squareroot of every value in a tensor (**note:** the elements need to be floats or this will error).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) - get the natural log of every value in a tensor (elements need to floats).
##### Finding the min, max, mean, sum (aggregation)

- To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:
* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean) - find the mean of all elements in a tensor.
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum) - find the sum of all elements in a tensor.
* **Note:** typically, each of these is under the `math` module, e.g. `tf.math.reduce_min()` but you can use the alias `tf.reduce_min()`.

- To find the variance & std, we need to access to `tensorflow_probability` library
```Python
import tensorflow_probability as tfp
tfp.stats.variance(E)
```
##### Finding the positional maximum and minimum
* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) - find the position of the maximum element in a given tensor.
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) - find the position of the minimum element in a given tensor.

In [55]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

- Using the TensorFlow function (where possible) has the advantage of being sped up later down the line when running as part of a [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs).
  - For example: the tensorflow function equivalent of the `*` (`multiply`) operator

In [56]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [67]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))

# Find the minimum
print(tf.reduce_min(E))
# Find the sum
print(tf.reduce_sum(E))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2505, shape=(), dtype=int64)


#### 1.3.4. Matrix Multiplication (Dot Product)
- Explain [Matrix Multiplication (Dot Product)](https://www.mathsisfun.com/algebra/matrix-multiplying.html).
- TensorFlow implements this matrix multiplication functionality in the [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) method.

![lining up dimensions for dot products](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-lining-up-dot-products.png)

In [62]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [63]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [64]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## 2. One-Hot Encoding

In [75]:
# Create a list of indices
some_list = [0, 1, 2, 3] # red, green, blue, purple

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

## 3. Using `@tf.function`
- `@tf.function` decorator case turns a Python function into a callable TensorFlow graph.
- TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the [Better performnace with tf.function](https://www.tensorflow.org/guide/function) guide.

In [79]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

## 4. GPUs Access
- Check if you've got access to a GPU using [`tf.config.list_physical_devices()`](https://www.tensorflow.org/guide/gpu).
- You can also find information about your NVIDA GPU using `!nvidia-smi`.

In [80]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [81]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

zsh:1: command not found: nvidia-smi
